### ISSUE TITLE
Dependency scanner for Gradle doesn't work

### ISSUE THREAD

**Issue by kwmyoo** [fosslight/fosslight_dependency_scanner#39]
**Describe the bug**
Dependency scanning for the Gradle package manager doesn't work. I have completed all the necessary prerequisites written on [https://fosslight.org/fosslight-guide/scanner/2_dependency.html#android-gradle](url). However when I try to scan a directory containing a `build.gradle` file, it outputs the error
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/dist-packages/coloredlogs/__init__.py", line 1140, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/fosslight_dependency", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/fosslight_dependency/analyze_dependency.py", line 1098, in main
    logger.error("Fail to generate result file. msg:()", msg)
Message: 'Fail to generate result file. msg:()'
Arguments: ('* There is no item to print in FOSSLight-Report.\n',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/fosslight_dependency", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/fosslight_dependency/analyze_dependency.py", line 1098, in main
    logger.error("Fail to generate result file. msg:()", msg)
Message: 'Fail to generate result file. msg:()'
Arguments: ('* There is no item to print in FOSSLight-Report.\n',)
### FINISH!! ###
```

**To Reproduce**
I'm not sure if I'm getting it right, but `dependency-license.*` files and `license-dependency.*` files are all empty in the `build/reports/license` directory. This seems to be causing the error.

**System environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python : 3.8

**Comment by dd-jy** [comment]
@kwmyoo 
Is it android application project or java project?
If you want to analyze the dependencies in java project with gradle, then you need to set tup the gradle prerequisite(https://fosslight.org/fosslight-guide/scanner/2_dependency.html#gradle) not android-gradle(https://fosslight.org/fosslight-guide-en/scanner/2_dependency.html#android-gradle).

**Comment by kwmyoo** [comment]
I used the wrong package manager. It works now.
